-- MySQL Script generated by MySQL Workbench
-- 04/30/18 11:37:30
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema videoquizz
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema videoquizz
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `videoquizz` DEFAULT CHARACTER SET utf8 ;
USE `videoquizz` ;

-- -----------------------------------------------------
-- Table `videoquizz`.`parametres`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `videoquizz`.`parametres` ;

CREATE TABLE IF NOT EXISTS `videoquizz`.`parametres` (
  `idparametre` INT(11) NOT NULL AUTO_INCREMENT,
  `nomparametre` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idparametre`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `videoquizz`.`quizz`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `videoquizz`.`quizz` ;

CREATE TABLE IF NOT EXISTS `videoquizz`.`quizz` (
  `idquizz` INT(11) NOT NULL AUTO_INCREMENT,
  `datequizz` DATE NULL DEFAULT NULL,
  `score` INT(11) NULL DEFAULT NULL,
  `idparametre` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`idquizz`),
  INDEX `FK_quizz_idparametre` (`idparametre` ASC),
  CONSTRAINT `FK_quizz_idparametre`
    FOREIGN KEY (`idparametre`)
    REFERENCES `videoquizz`.`parametres` (`idparametre`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `videoquizz`.`videos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `videoquizz`.`videos` ;

CREATE TABLE IF NOT EXISTS `videoquizz`.`videos` (
  `idvideos` INT(11) NOT NULL AUTO_INCREMENT,
  `titrevideo` VARCHAR(45) NULL DEFAULT NULL,
  `description` VARCHAR(45) NULL DEFAULT NULL,
  `videos` TEXT NULL DEFAULT NULL,
  `imagepochette` MEDIUMBLOB NULL DEFAULT NULL,
  PRIMARY KEY (`idvideos`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `videoquizz`.`contenir`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `videoquizz`.`contenir` ;

CREATE TABLE IF NOT EXISTS `videoquizz`.`contenir` (
  `idvideos` INT(11) NOT NULL,
  `idquizz` INT(11) NOT NULL,
  PRIMARY KEY (`idvideos`, `idquizz`),
  INDEX `FK_contenir_idquizz` (`idquizz` ASC),
  CONSTRAINT `FK_contenir_idquizz`
    FOREIGN KEY (`idquizz`)
    REFERENCES `videoquizz`.`quizz` (`idquizz`),
  CONSTRAINT `FK_contenir_idvideos`
    FOREIGN KEY (`idvideos`)
    REFERENCES `videoquizz`.`videos` (`idvideos`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `videoquizz`.`utilisateurs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `videoquizz`.`utilisateurs` ;

CREATE TABLE IF NOT EXISTS `videoquizz`.`utilisateurs` (
  `idutilisateur` INT(11) NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NULL DEFAULT NULL,
  `pseudo` VARCHAR(45) NULL DEFAULT NULL,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  `mdp` VARCHAR(45) NULL DEFAULT NULL,
  `avatar` MEDIUMBLOB NULL DEFAULT NULL,
  `status` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`idutilisateur`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `videoquizz`.`definir`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `videoquizz`.`definir` ;

CREATE TABLE IF NOT EXISTS `videoquizz`.`definir` (
  `idutilisateur` INT(11) NOT NULL,
  `idparametre` INT(11) NOT NULL,
  PRIMARY KEY (`idutilisateur`, `idparametre`),
  INDEX `FK_definir_idparametre` (`idparametre` ASC),
  CONSTRAINT `FK_definir_idparametre`
    FOREIGN KEY (`idparametre`)
    REFERENCES `videoquizz`.`parametres` (`idparametre`),
  CONSTRAINT `FK_definir_idutilisateur`
    FOREIGN KEY (`idutilisateur`)
    REFERENCES `videoquizz`.`utilisateurs` (`idutilisateur`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `videoquizz`.`typevideos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `videoquizz`.`typevideos` ;

CREATE TABLE IF NOT EXISTS `videoquizz`.`typevideos` (
  `idtypevideo` INT(11) NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(45) NULL DEFAULT NULL,
  `idvideos` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`idtypevideo`),
  INDEX `FK_TypeVideos_idvideos` (`idvideos` ASC),
  CONSTRAINT `FK_TypeVideos_idvideos`
    FOREIGN KEY (`idvideos`)
    REFERENCES `videoquizz`.`videos` (`idvideos`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
